Implement localStorage API
stellar-fighter/stellar-fighter pull request #54
Opened 2019-05-27 17:00 UTC by yun0000

#8 
아직 점수가 구현되지 않아서, 더미 스코어를 이용하여 숫자 값의 배열을 localStorage에 ranking으로 저장하였습니다
아직 완전히 구현하지 못했지만
이걸 game over와 마찬가지로 fillText 를 이용하여 보여주는게 맞을지 여쭤보고자 리퀘스트 드립니다..!

2019-05-28 05:43 UTC, gonapps commented
아마 게임 중간에는 fillText로 보여주면 될 것 같고 게임 끝나고 히스토리 볼 때는 HTML로 보여주지 않을까 싶네요

2019-05-28 06:19 UTC, gonapps commented
그리고 SDS에는 
ranking에 {time, score, name, ranking} 이런 식의 필드가 있는데
ranking.ranking은 뭔가 어색하니 이름을 바꿔보는 것도 좋을 것 같네요
record.ranking도 괜찮을 것 같고..

2019-05-28 09:04 UTC, yun0000 commented
> 그리고 SDS에는
> ranking에 {time, score, name, ranking} 이런 식의 필드가 있는데
> ranking.ranking은 뭔가 어색하니 이름을 바꿔보는 것도 좋을 것 같네요
> record.ranking도 괜찮을 것 같고..

아아 넵~! 참고해서 고치겠습니다

2019-05-28 12:08 UTC, yun0000 commented
> 그리고 SDS에는
> ranking에 {time, score, name, ranking} 이런 식의 필드가 있는데
> ranking.ranking은 뭔가 어색하니 이름을 바꿔보는 것도 좋을 것 같네요
> record.ranking도 괜찮을 것 같고..

팀장님 이름을 게임 시작 전에 html 폼 이용해서 입력받는 방식인가요?
점수는 일단 1초당 1점씩 받는 부분을 만들어보고 그걸로 저장받는 방식으로 했는데, 적이 죽었을 때 점수를 어떻게 넣어야할지 몰라서 그 부분은 아직 구현을 못했습니다 ㅠㅠ

일단 지금까지 한 건, 게임을 진행하면 좌상단에 점수가 1초당 1점씩 추가되는 점수 보여주는 것이랑,
게임이 끝나면 점수만 랭킹을 보여주는 부분입니닷 ㅠㅠ
![image](https://user-images.githubusercontent.com/33647613/58476689-7a5f9600-818c-11e9-8ae5-7b651c13e3a3.png)

2019-05-28 12:40 UTC, binkoni requested changes
변경 필요

2019-05-28 12:40 UTC, gonapps commented on src/scene_nodes.js
> +    ctx.fillStyle = '#FFFFFF';
Background에 기능을 추가하는 것 보다는
SceneNode를 확장한 새 클래스를 만들어서 하는게 더 좋을 것 같습니다.

2019-05-28 12:40 UTC, gonapps commented on src/states.js
> +    this.previousTime = new Date().getTime();
기존의 timer 사용해주세요

2019-05-28 12:40 UTC, gonapps commented on src/states.js
> +    for (var i = 0;i < 10;i++) {
var 대신 let 사용 권장

2019-05-28 12:40 UTC, gonapps commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
var 대신 const 사용 권장, ranking보다 적절한 이름이 있으면 변경 필요. (records?)

2019-05-28 12:44 UTC, gonapps commented
적이 죽었을 때 점수는 현재로서는 HpSystem에서 entity 제거할 때 TeamComp를 검사해서 ENEMY면 점수를 주면 될 것 같습니다.

2019-05-29 07:07 UTC, yun0000 commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
이름은 records로 변경했고, 만약 null일때 뒤에 빈 배열로 재정의가 필요할것같아서 var은 그대로 했습니다!
근데 bullet도 현재 enemy여서 쏴서 없애면 Alien이랑 똑같은 점수를 받는데, ENEMY 아니고 BULLET으로 바꿔도 될까요??

2019-05-29 07:11 UTC, yun0000 commented on src/states.js
> +    this.previousTime = new Date().getTime();
timer 클래스는 어떻게 쓰는지 아직 모르겠어서 ㅠㅠ 고민해보고 변경하겠습니다..

2019-05-29 07:50 UTC, gonapps commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
> 이름은 records로 변경했고, 만약 null일때 뒤에 빈 배열로 재정의가 필요할것같아서 var은 그대로 했습니다!

그렇다면 var 대신 let 쓰시면 됩니다

> 근데 bullet도 현재 enemy여서 쏴서 없애면 Alien이랑 똑같은 점수를 받는데, ENEMY 아니고 BULLET으로 바꿔도 될까요??

적의 종류별로 점수를 다르게 주는 부분은 나중에 ScoreComp를 추가해서 처리하는게 더 좋을 것 같습니다.

2019-05-29 08:43 UTC, yun0000 commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
넵! let으로 변경했습니다
ScoreComp는 새 이슈로 만들어서 하면 될까요??

2019-05-29 08:49 UTC, gonapps commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
아 네 그러셔도 돼요

2019-05-29 12:15 UTC, yun0000 commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
추가했습니다! 근데 이거 댓글 안달아도 추가한지 아시나요???
아니면 따로 댓글 안달아도 커밋하면 알림이 가나요???

2019-05-30 00:01 UTC, gonapps commented on src/states.js
> +    var ranking = JSON.parse(localStorage.getItem("record"));
아 네 중간에 추가한 커밋들은 따로 알림 안가고 댓글만 알림이 갑니다

2019-05-30 00:08 UTC, merged