Dnfkabranch
stellar-fighter/stellar-fighter pull request #58
Opened 2019-06-01 15:25 UTC by rnjsdnfka

2019-06-01 15:37 UTC, binkoni requested changes
[lint 에러](https://travis-ci.org/stellar-fighter/stellar-fighter/builds/540123913?utm_source=github_status&utm_medium=notification) 해결 & 코드 수정 필요

2019-06-01 15:37 UTC, gonapps commented on src/vec.js
> +    this.x + vec.x;
코드부분들 전부 버그 있어서 코드 고쳐놓은건데 다시 원래대로 바꿔주세요

2019-06-01 16:07 UTC, binkoni requested changes
'@return'도 사용 필요

2019-06-01 16:07 UTC, gonapps commented on src/vec.js
> +   */
'@param'만 아니라 '@return' 도 쓰셨으면 좋겠네요

2019-06-02 02:40 UTC, rnjsdnfka commented on src/vec.js
> +    this.x + vec.x;
코드 고친건없었는데... 이상하네요 알겠습니다

2019-06-02 06:33 UTC, gonapps commented
master 브랜치로 보내주셔서 닫겠습니다
dev 브랜치로 보내주세요

2019-06-02 06:33 UTC, closed without merging

2019-06-05 08:24 UTC, gonapps commented on src/vec.js
> +    this.x + vec.x;
코드 몇 줄만 고치면 되는데 아직인가요..